### ISSUE TITLE
Please give permission to use your code.

### ISSUE THREAD

**Issue by Chris2011** [markiewb/restart-ide-for-netbeans#2]
Hey benno,

due to Apache legal stuff, the apache developer community need your explicit permission that I can use your code. So this is the ticket for that, I will link that in my PR which moves your code to the core code.

So please write clear opinion and permission for me to use your code.

Cheers

Chris

**Comment by markiewb** [comment]
Yes, I allow you to use the code. It is already Apache 2.0 licensed, so it is easier to integrate into Apache NetBeans.

If you like I can also transfer the project to your ownership.

**Comment by Chris2011** [comment]
> If you like I can also transfer the project to your ownership.

Thx Benno, that would be cool :)

**Comment by Chris2011** [comment]
Done
